name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEPLOY_VER: ${{github.sha}}
  YEAR: 1111
  
permissions:
  packages: read
  contents: read
  actions: read
  deployments: read
  discussions: read
  issues: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: step 1
        run: ls

      - name: step 2
        run: cat ./Task1/log.txt

      - name: step 3
        run: echo "Hello from ${DEPLOY_VER} commit"

  build2:
    needs: build1
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MONTH: June

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: step 1 of job 2
        run: |
          date
          echo "Day - $DAY__OF_THE_MONTH";
          echo Month - "$MONTH";
          echo Year - "$YEAR";
          echo My favorite day of week is - "$FAVORITE_DAY_OF_WEEK";
        env:
          DAY__OF_THE_MONTH: 22

  build3:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - name: checkout curr repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout another PRIVATE repo alongside
        uses: actions/checkout@v3
        with:
          repository: OlexandrPodustov/actions
          ref: main
          path: tttestfldr
          token: ${{ secrets.ACCESS_TOKEN }}
